development:
  adapter: redis

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: project_management_production
  driver: :ruby
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
